#!/bin/sh

alias ls='ls -AF --group-directories-first --color=auto'
alias lr='ls -ARF --group-directories-first --color=auto'
alias ll='ls -AlF --group-directories-first --color=auto'
alias lt='ls -AltF --sort=time --group-directories-first --color=auto'
alias grep='grep --colour=auto'

# Confirm command
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# 
alias discord='flatpak run com.discordapp.Discord'
#alias steam='flatpak run --filesystem=/mnt com.valvesoftware.Steam'

